function fp = atlas_cache_fingerprint_legacy_rs3(familyName, mu, CJ, cfg)
%ATLAS_CACHE_FINGERPRINT_LEGACY_RS3  Reproduce the PRE-RENAME fingerprint
% format (literal 'rs3|' prefix) used by atlas caches built before the
% rs3_* → atlas_* rename documented in CHANGELOG.md.
%
% This is a read-only compatibility shim: it exists ONLY so that cache
% files built under the old scheme can still be located and validated by
% their exact original fingerprint string. It intentionally does NOT
% replace or modify atlas_cache_fingerprint.m (which correctly uses the
% current 'atlas|' prefix for anything built going forward).
%
% Field order/formatting is identical to atlas_cache_fingerprint.m — only
% the literal prefix differs.

if isstring(familyName), familyName = char(familyName); end

fp = sprintf([ ...
    'rs3|%s|mu=%.16g|CJ=%.16g|' ...
    'grid:R=%.16g,dx=%.16g,dy=%.16g,dth=%.16g|' ...
    'seed:TfS=%.16g,N=%d,ds=%.16g,yE=%.16g,minSeg=%d|' ...
    'fan:dth=%.16g,DV=%.16g|' ...
    'prop:T=%.16g,rt=%.16g,at=%.16g,v2=%.16g|' ...
    'log:seg=%d,frac=%.16g,slf=%.16g,msf=%.16g|' ...
    'ver=%s' ], ...
    familyName, mu, CJ, ...
    cfg.grid.Rdom, cfg.grid.dx, cfg.grid.dy, cfg.grid.dtheta, ...
    cfg.seed.Tf_scale, cfg.seed.N_dense, cfg.seed.ds_seed, cfg.seed.y_eps, cfg.seed.minSegPts, ...
    cfg.fan.dtheta_fan, cfg.fan.DV_cap_nd, ...
    cfg.propag.Tmax, cfg.propag.relTol, cfg.propag.absTol, cfg.propag.v2tol, ...
    cfg.log.segwalk.enable, cfg.log.segwalk.frac, cfg.log.step_len_factor, cfg.log.maxstep_factor, ...
    cfg.cache.version_tag);
end
