function fp = atlas_cache_fingerprint(familyName, mu, CJ, cfg)
%RS3_CACHE_FINGERPRINT_FAMILY  Deterministic fingerprint string for family atlas cache.
% Includes ONLY atlas-relevant knobs to decide cache validity.

if isstring(familyName), familyName = char(familyName); end

% NOTE: keep this list stable (changing it invalidates cache automatically).
fp = sprintf([ ...
    'rs3|%s|mu=%.16g|CJ=%.16g|' ...
    'grid:R=%.16g,dx=%.16g,dy=%.16g,dth=%.16g|' ...
    'seed:TfS=%.16g,N=%d,ds=%.16g,yE=%.16g,minSeg=%d|' ...
    'fan:dth=%.16g,DV=%.16g|' ...
    'prop:T=%.16g,rt=%.16g,at=%.16g,v2=%.16g|' ...
    'log:seg=%d,frac=%.16g,slf=%.16g,msf=%.16g|' ...
    'ver=%s' ], ...
    familyName, mu, CJ, ...
    cfg.grid.Rdom, cfg.grid.dx, cfg.grid.dy, cfg.grid.dtheta, ...
    cfg.seed.Tf_scale, cfg.seed.N_dense, cfg.seed.ds_seed, cfg.seed.y_eps, cfg.seed.minSegPts, ...
    cfg.fan.dtheta_fan, cfg.fan.DV_cap_nd, ...
    cfg.propag.Tmax, cfg.propag.relTol, cfg.propag.absTol, cfg.propag.v2tol, ...
    cfg.log.segwalk.enable, cfg.log.segwalk.frac, cfg.log.step_len_factor, cfg.log.maxstep_factor, ...
    cfg.cache.version_tag);
end
